repos:
  - repo: local
    hooks:
      - id: fix-and-check-all
        name: Fix and check all
        entry: uv run poe fix-and-check-all
        language: system
        stages: [pre-push]
        pass_filenames: false
